# Generated by Django 3.2.5 on 2021-07-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('py_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pyarticles',
            name='comment',
        ),
    ]
