# Generated by Django 3.2.5 on 2021-07-13 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('py_blog', '0002_remove_pyarticles_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyarticles',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
